# Generated by Django 3.2.6 on 2021-10-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='profile_files/'),
        ),
        migrations.AddField(
            model_name='info',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
